@startuml
'https://plantuml.com/class-diagram
skinparam ClassAttributeIconSize 0
hide circle

interface Command <<interface>> {
    + execute(CourseManager, SessionManager) : void
    + isExit() : boolean
}

class AddCourseCommand {
    - input : String
    + execute(CourseManager, SessionManager) : void
    + isExit() : boolean
}

class AddSessionCommand {
    - input : String
    + execute(CourseManager, SessionManager) : void
    + isExit() : boolean
}

class DeleteCourseCommand {
    - input : String
    + execute(CourseManager, SessionManager) : void
    + isExit() : boolean
}

class DeleteSessionByDateCommand {
    - dateString : String
    + execute(CourseManager, SessionManager) : void
    + isExit() : boolean
}

class DeleteSessionByIndexCommand {
    - courseName : String
    - IndexString : String
    + execute(CourseManager, SessionManager) : void
    + isExit() : boolean
}

class EditCourseNameCommand {
    - oldCourseName : String
    - newCourseName : String
    + execute(CourseManager, SessionManager) : void
    + isExit() : boolean
}

class EditSessionCommand {
    - input : String
    + execute(CourseManager, SessionManager) : void
    + isExit() : boolean
}

class ExitCommand {
    + execute(CourseManager, SessionManager) : void
    + isExit() : boolean
}

class FilterByDateCommand {
    - dateString : String
    + execute(CourseManager, SessionManager) : void
    + isExit() : boolean
}

class FilterByNameAndDateCommand {
    - courseKeyword : String
    - dateString : String
    + execute(CourseManager, SessionManager) : void
    + isExit() : boolean
}

class FilterByName {
    - keyword : String
    + execute(CourseManager, SessionManager) : void
    + isExit() : boolean
}

class ListCourseCommand {
    + execute(CourseManager, SessionManager) : void
    + isExit() : boolean
}

class ListCourseHoursPerSessionCommand {
    - input : String
    + execute(CourseManager, SessionManager) : void
    + isExit() : boolean
}

class ResetCourseHoursCommand {
    - input : String
    + execute(CourseManager, SessionManager) : void
    + isExit() : boolean
}

class HelpCommand {
    + execute(CourseManager, SessionManager) : void
    + isExit() : boolean
}

AddCourseCommand -[hidden]down- AddSessionCommand
AddSessionCommand -[hidden]down- DeleteCourseCommand
DeleteCourseCommand -[hidden]down- DeleteSessionByDateCommand
DeleteSessionByDateCommand -[hidden]down- DeleteSessionByIndexCommand
DeleteSessionByIndexCommand -[hidden]down- EditCourseNameCommand
EditCourseNameCommand -[hidden]down- HelpCommand
EditSessionCommand -[hidden]down- ExitCommand
ExitCommand -[hidden]down- FilterByDateCommand
FilterByDateCommand -[hidden]down- FilterByNameAndDateCommand
FilterByNameAndDateCommand -[hidden]down- FilterByName
FilterByName -[hidden]down- ListCourseCommand
ListCourseCommand -[hidden]down- ListCourseHoursPerSessionCommand
ListCourseHoursPerSessionCommand -[hidden]down- ResetCourseHoursCommand

AddCourseCommand .up.|> Command
AddSessionCommand .up.|> Command
DeleteCourseCommand .up.|> Command
DeleteSessionByDateCommand .up.|> Command
DeleteSessionByIndexCommand .up.|> Command
EditCourseNameCommand .up.|> Command
HelpCommand .up.|> Command

EditSessionCommand .up.|> Command
ExitCommand .up.|> Command
FilterByDateCommand .up.|> Command
FilterByNameAndDateCommand .up.|> Command
FilterByName .up.|> Command
ListCourseCommand .up.|> Command
ListCourseHoursPerSessionCommand .up.|> Command
ResetCourseHoursCommand .up.|> Command


@enduml