@startuml
skinparam ClassAttributeIconSize 0
hide circle

class Course {
    - courseName : String
    + Course(courseName: String)
    + getCourseName() : String
    + setCourseName(courseName: String) : void
    + toString() : String
    + toStorageString() : String
}

class CourseManager {
    + add(course: Course) : void
    + delete(course: Course) : void
    + getCourses() : ArrayList<Course>
    + findCourse(courseName: String) : Course
    + iterator() : Iterator<Course>
}

CourseManager "1" --- "0..*" Course : manages >
@enduml
