@startuml
title Activity Diagram for DeleteCourseCommand.execute()

skinparam ActivityStartColor #Gray
skinparam ActivityEndColor #Gray
skinparam ActivityDiamondBackgroundColor #Wheat
skinparam Padding 1
skinparam ParticipantPadding 1
skinparam BoxPadding 1
skinparam conditionStyle diamond

start
:User enter delete course command;

if () then ([Input empty])
    :Prompt user to specify <course>;
    stop
else ([Input is not empty])
    :Find the Course in CourseManager;
    :Set [courseToDelete];
endif

if () then ([courseToDelete does not exist])
    :Alert [courseToDelete] non-existent;
    stop
else ([courseToDelete exist])
    :Prompt user for 'y' or 'n';
endif

if () then ([Input is 'n'])
    :Inform user that course has not been deleted;
    stop
else ([Input is 'y'])
    :Delete all Sessions and the Course;

if () then ([courseToDelete does not exist])
    :Developer Log INFO "Successfully deleted course";
else ([courseToDelete exist])
    :Alert User deletion error;
    stop
endif
stop
@enduml