@startuml
title Activity Diagram for ListCourseCommand.execute()

skinparam ActivityStartColor #Gray
skinparam ActivityEndColor #Gray
skinparam ActivityDiamondBackgroundColor #Wheat
skinparam Padding 1
skinparam ParticipantPadding 1
skinparam BoxPadding 1
skinparam conditionStyle diamond

start
:User issues the `list` command;

if () then ([Input empty])
    :AssertionError thrown;
    stop
else ([Input is not empty])
    :Developer Log INFO "Executing ListCourseCommand";
endif

if () then ([course list is empty])
    :UserInterface prints "No courses available";
    stop
else ([course list not empty])
    :Call UserInterface.printCourseList(courses);
endif

:Developer Log FINE "Finished ListCourseCommand";
stop
@enduml
