@startuml
title Activity Diagram for ListCourseCommand.execute()

skinparam ActivityStartColor #Gray
skinparam ActivityEndColor #Gray
skinparam ActivityDiamondBackgroundColor #Wheat
skinparam Padding 1
skinparam ParticipantPadding 1
skinparam BoxPadding 1

start

:Assert courses != null;
if (assertion failed?) then (yes)
    :AssertionError thrown;
    stop
else (no)
    :Assert sessions != null;
    if (assertion failed?) then (yes)
        :AssertionError thrown;
        stop
    else (no)
        :Developer Log [INFO] "Executing ListCourseCommand";
    endif
endif

if (course list is empty?) then (yes)
    :UserInterface prints "No courses available";
    stop
else (no)
    :Call UserInterface.printCourseList(courses);
endif

:Developer Log [FINE] "Finished ListCourseCommand";
stop
@enduml
