@startuml
'https://plantuml.com/activity-diagram-beta

skinparam ActivityStartColor #Gray
skinparam ActivityEndColor #Gray
skinparam ActivityDiamondBackgroundColor #Wheat
skinparam Padding 1
skinparam ParticipantPadding 1
skinparam BoxPadding 1
skinparam conditionStyle diamond

start

:User enters reset command;

if () then ([Input is empty])
    :Prompt user to specify <course> or all;
    stop
else ([Input is not empty])

if () then ([Input is "all"])
    :Set [target] = "all";
    :Set [safeword] = "RESET ALL";

else ([Input is <course>])
    :Find course in CourseManager;
    if () then ([<course> is not found])
        :Alert <course> non-existent;
        stop
    else ([<course> is found])
    :Set [target] = <course>;
    :Set [safeword] = "RESET";
    endif
endif

:Prompt user for 'y' or 'n' (first confirmation);

if () then ([Input is 'n'])
    :Alert cancelled reset;
    stop
else ([Input is 'y'])

:Prompt user for exact [safeword];

if () then ([Input is not exactly <safeword>])
    :Alert cancelled reset;
    stop
else ([Input is exactly <safeword>])

:Clear [target] sessions;
:Alert successful reset;

stop
@enduml