@startuml
'https://plantuml.com/sequence-diagram

participant ":App" as App
participant ":Storage" as Storage
participant "dataFile:File" as File
participant ":BufferedReader" as BR


App ->> Storage: load(courses, sessions)
activate Storage

Storage -> Storage: ensureParentDirectoryExists()
activate Storage

Storage -> File: getParentFile()
activate File

File --> Storage: parent : File
deactivate File

opt parent != null && !parent.exists()
    Storage -> File: mkdirs()
    activate File

    File --> Storage: result : boolean
    deactivate File
end

Storage -> File: exists()
activate File
File --> Storage: result : boolean
deactivate File

opt file does not exist
    note right of Storage: No previous storage,\nstarting with new dataset
    Storage --> App
    deactivate Storage
end

Storage -> BR**: new BufferedReader(FileReader(dataFile))
activate BR

Storage -> Storage: loadData(courses, sessions, buffer)
activate Storage

    Storage -> ArrayList**: new ArrayList<>()
    activate ArrayList
    ArrayList --> Storage: ignoredEntries : ArrayList<String>
    deactivate ArrayList

loop while next line is not null
Storage -> BR: readLine()
    BR --> Storage: line : String
    ref over BR, Storage
        parsing courses or sessions
    end
end

Storage --> Storage:
deactivate Storage

Storage -> BR: close()
deactivate BR
destroy BR
Storage --> App
deactivate Storage

@enduml